apiVersion: v1
kind: Service
metadata:
  labels:
   k8s-app: k8s_python_sample_code
  name: pythonsvc
  namespace: python
spec:
  type: NodePort
  ports:
  - port: 5035
  selector:
   k8s-app: k8s_python_sample_code