apiVersion: v1
kind: Pod
metadata:
  name: command-demo
  namespace: python
  labels:
    purpose: demonstrate-command
spec:
  containers:
  - name: command-demo-container
    image: xxxuhong.azurecr.io/python:v1
    command: ["printenv"]
    args: ["HOSTNAME", "KUBERNETES_PORT"]
  restartPolicy: OnFailure